### ISSUE TITLE
confusing sasl log messages from k8s healthchecks probably

### ISSUE THREAD

**Issue by maxgruber19** [stackabletech/hive-operator#530]
### Affected Stackable version

24.7.0

### Affected Apache Hive version

3.1.3

### Current and expected behavior

when enabling kerberos exceptions are logged continously because the kubernetes readiness and liveness checks don't pay attention to the sasl requirements of the metastore. currently 98 percent of the metastore log consists of those irrelevant messages

with all those messages we don't find what we're looking for in the logs and alerting is tricky when paying attention to any kind of exception thrown 

```
2024-11-06T16:37:07,325 ERROR [pool-7-thread-198] server.TThreadPoolServer: Error occurred during processing of message.
java.lang.RuntimeException: org.apache.thrift.transport.TSaslTransportException: No data or no sasl data in the stream
    at org.apache.thrift.transport.TSaslServerTransport$Factory.getTransport(TSaslServerTransport.java:219) ~[libthrift-0.9.3.jar:0.9.3]
    at org.apache.hadoop.hive.metastore.security.HadoopThriftAuthBridge$Server$TUGIAssumingTransportFactory$1.run(HadoopThriftAuthBridge.java:694) ~[hive-standalone-metastore-3.1.3.jar:3.1.3]
    at org.apache.hadoop.hive.metastore.security.HadoopThriftAuthBridge$Server$TUGIAssumingTransportFactory$1.run(HadoopThriftAuthBridge.java:691) ~[hive-standalone-metastore-3.1.3.jar:3.1.3]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
    at javax.security.auth.Subject.doAs(Subject.java:361) ~[?:?]
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1855) ~[hadoop-common-3.3.4.jar:?]
    at org.apache.hadoop.hive.metastore.security.HadoopThriftAuthBridge$Server$TUGIAssumingTransportFactory.getTransport(HadoopThriftAuthBridge.java:691) ~[hive-standalone-metastore-3.1.3.jar:3.1.3]
    at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:269) [libthrift-0.9.3.jar:0.9.3]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
    at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.apache.thrift.transport.TSaslTransportException: No data or no sasl data in the stream
    at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:328) ~[libthrift-0.9.3.jar:0.9.3]
    at org.apache.thrift.transport.TSaslServerTransport.open(TSaslServerTransport.java:41) ~[libthrift-0.9.3.jar:0.9.3]
    at org.apache.thrift.transport.TSaslServerTransport$Factory.getTransport(TSaslServerTransport.java:216) ~[libthrift-0.9.3.jar:0.9.3]

```

### Possible solution

providing a more compliant readiness / liveness probe or somehow hide these exceptions in the log

### Additional context

i can barely remember us talking about that, not sure wether there is an issue for that yet so feel free to close if already issued

### Would you like to work on fixing this bug?

None

**Comment by Jimvin** [comment]
Agreed, enabling Kerberos does create a lot a noise in the logs. In lieu of a more intelligent health check, these messages can be suppressed by reducing the logging for TThreadPoolServer.

```
spec:
  metastore:
    config:
      logging:
        containers:
          hive:
            loggers:
              org.apache.thrift.server.TThreadPoolServer:
                level: NONE
```

**Comment by maxgruber19** [comment]
thanks @Jimvin, that's a pretty good fix for the moment. does the job 👍🏼
